name: build test

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    strategy:
      matrix:
        version: ['test', 'prod']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Build
        run: go build -o hello-world main.go

      - name: Run
        if: "endsWith(inputs.runner, 'os-latest')"
        run: ./hello-world

      - name: Set artifact name
        id: set_artifact
        run: |
          postfix="${{ matrix.version }}"
          if [[ "${{ inputs.runner }}" == "ubuntu-latest" ]]; then
            echo "artifact_name=ub-${postfix}" >> $GITHUB_OUTPUT
          else
            echo "artifact_name=mac-${postfix}" >> $GITHUB_OUTPUT
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.set_artifact.outputs.artifact_name }}
          path: hello-world