on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string

jobs:
  test-things:
    runs-on: ${{ toJSON(inputs.runs-on) }}
    steps:
      - name: Read inputs
        run: |
          echo "${{ toJSON(inputs.runs-on) }}"
          printf "%s" "${{ toJSON(inputs.runs-on) }}"