on:
  workflow_call:
    inputs:
      data-list:
        required: true
        type: string

jobs:
  test-things:
    runs-on: ubuntu-latest
    steps:
      - name: Read inputs
        run: |
          echo "${{ toJSON(inputs.data-list) }}"
          printf "%s" "${{ toJSON(inputs.data-list) }}"