name: build test

on:
  workflow_call:
    inputs:
      runner-name:
        required: true
        type: string
      data:
        required: true
        type: string

jobs:
  do-things:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Data
        id: gen_data
        run: |
          echo -n "out=Data generated for ${{ inputs.data }}" > "data_${{ inputs.data }}.txt"

      - name: Save spread test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "results-${{ github.run_id }}-${{ github.run_attempt }}-${{ inputs.runner-name }}" 
          path: "data_${{ inputs.data }}.txt"