name: build test

on:
  workflow_call:
    inputs:
      data:
        required: true
        type: string

jobs:
  do-things:
    runs-on: ubuntu-latest
    outputs:
      out: ${{ steps.gen_data.outputs.out }}
    steps:
      - name: Generate Data
        id: gen_data
        run: |
          echo -n "out=Data generated for ${{ inputs.data }}" > "${{ github.workspace }}/.data"

      - name: Save spread test results to cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: "${{ github.workspace }}/.data"
          key: "${{ github.job }}-results-${{ github.run_id }}-${{ github.run_attempt }}-${{ inputs.data }}"