name: build test

on:
  workflow_call:
    inputs:
      data:
        required: true
        type: string
    outputs:
      out:
        value: ${{ jobs.do-things.outputs.out }}

jobs:
  do-things:
    runs-on: ubuntu-latest
    outputs:
      out: ${{ steps.gen_data.outputs.out }}
    steps:
      - name: Generate Data
        id: gen_data
        run: |
          echo -n "out=Data generated for ${{ inputs.data }}" >> $GITHUB_OUTPUT
  check:
    runs-on: ubuntu-latest
    needs: do-things
    steps:
      - name: Check
        run: |
          echo '${{ toJSON(needs.do-things.outputs) }}'