name: build test

on:
  workflow_call:
    inputs:
      runner-name:
        required: true
        type: string
      group:
        required: true
        type: string

jobs:
  do-things:
    runs-on: ubuntu-latest
    steps:
      - name: Get job name
        run: echo "${{ github.job }}"
      
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Generate Data (1)
        if: ${{ inputs.group == 'ubuntu-18' }}
        run: |
          cat <<EOF > example-${{ inputs.runner-name }}.json
          [
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "15:33:10",
              "verb": "Allocating",
              "task": null,
              "extra": "google:ubuntu-18.04-64..."
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "15:33:24",
              "verb": "Waiting",
              "task": null,
              "extra": "for google:ubuntu-18.04-64 (nov221433-883591) to boot at 34.147.148.247..."
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "15:34:05",
              "verb": "Allocated",
              "task": null,
              "extra": "google:ubuntu-18.04-64 (nov221433-883591)."
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "15:34:05",
              "verb": "Connecting",
              "task": null,
              "extra": "to google:ubuntu-18.04-64 (nov221433-883591)..."
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "15:34:05",
              "verb": "Connected",
              "task": null,
              "extra": "to google:ubuntu-18.04-64 (nov221433-883591) at 34.147.148.247."
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "15:34:05",
              "verb": "Sending",
              "task": null,
              "extra": "project content to google:ubuntu-18.04-64 (nov221433-883591)..."
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "15:34:10",
              "verb": "Preparing",
              "task": "google:ubuntu-18.04-64"
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "15:36:13",
              "verb": "Preparing",
              "task": "google:ubuntu-18.04-64:tests/main/"
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "15:37:10",
              "verb": "Preparing",
              "task": "google:ubuntu-18.04-64:tests/main/snapd-update-services"
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "15:37:32",
              "verb": "Rebooting",
              "task": null,
              "extra": "on nov221433-883591 (google:ubuntu-18.04-64:tests/main/snapd-update-services) as requested..."
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "15:39:12",
              "verb": "Executing",
              "task": "google:ubuntu-18.04-64:tests/main/snapd-update-services"
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "15:40:33",
              "verb": "Restoring",
              "task": "google:ubuntu-18.04-64:tests/main/snapd-update-services"
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "15:41:18",
              "verb": "Restoring",
              "task": "google:ubuntu-18.04-64:tests/main/"
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "15:41:32",
              "verb": "Restoring",
              "task": "google:ubuntu-18.04-64"
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "15:41:33",
              "verb": "Discarding",
              "task": null,
              "extra": "google:ubuntu-18.04-64 (nov221433-883591)..."
          },
          {
              "type": "result",
              "date": "2024-11-22",
              "time": "15:41:33",
              "result_type": "Successful",
              "level": "tasks",
              "stage": null,
              "number": "1",
              "detail": null
          },
          {
              "type": "result",
              "date": "2024-11-22",
              "time": "15:41:33",
              "result_type": "Aborted",
              "level": "tasks",
              "stage": null,
              "number": "0",
              "detail": null
          }
          ]
          EOF

      - name: Generate Data (2)
        if: ${{ inputs.group == 'ubuntu-24' }}
        run: |
          cat <<EOF > example-${{ inputs.runner-name }}.json
          [
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "14:22:34",
              "verb": "Allocating",
              "task": null,
              "extra": "google:ubuntu-24.04-64..."
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "14:22:46",
              "verb": "Waiting",
              "task": null,
              "extra": "for google:ubuntu-24.04-64 (nov221322-189537) to boot at 34.105.195.110..."
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "14:23:17",
              "verb": "Allocated",
              "task": null,
              "extra": "google:ubuntu-24.04-64 (nov221322-189537)."
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "14:23:17",
              "verb": "Connecting",
              "task": null,
              "extra": "to google:ubuntu-24.04-64 (nov221322-189537)..."
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "14:23:18",
              "verb": "Connected",
              "task": null,
              "extra": "to google:ubuntu-24.04-64 (nov221322-189537) at 34.105.195.110."
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "14:23:18",
              "verb": "Sending",
              "task": null,
              "extra": "project content to google:ubuntu-24.04-64 (nov221322-189537)..."
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "14:23:22",
              "verb": "Preparing",
              "task": "google:ubuntu-24.04-64"
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "14:25:42",
              "verb": "Preparing",
              "task": "google:ubuntu-24.04-64:tests/main/"
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "14:26:45",
              "verb": "Preparing",
              "task": "google:ubuntu-24.04-64:tests/main/ack"
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "14:26:58",
              "verb": "Executing",
              "task": "google:ubuntu-24.04-64:tests/main/ack"
          },
          {
              "type": "info",
              "date": "2024-11-22",
              "time": "14:26:58",
              "info_type": "Error",
              "verb": "executing",
              "task": "google:ubuntu-24.04-64:tests/main/ack",
              "extra": null,
              "detail": null
          },
          {
              "type": "info",
              "date": "2024-11-22",
              "time": "14:26:58",
              "info_type": "Debug",
              "verb": null,
              "task": "google:ubuntu-24.04-64:tests/main/ack",
              "extra": null,
              "detail": null
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "14:26:58",
              "verb": "Restoring",
              "task": "google:ubuntu-24.04-64:tests/main/ack"
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "14:27:23",
              "verb": "Restoring",
              "task": "google:ubuntu-24.04-64:tests/main/"
          },
          {
              "type": "phase",
              "date": "2024-11-22",
              "time": "14:27:31",
              "verb": "Restoring",
              "task": "google:ubuntu-24.04-64"
          },
          {
              "type": "action",
              "date": "2024-11-22",
              "time": "14:27:32",
              "verb": "Discarding",
              "task": null,
              "extra": "google:ubuntu-24.04-64 (nov221322-189537)..."
          },
          {
              "type": "result",
              "date": "2024-11-22",
              "time": "14:27:32",
              "result_type": "Successful",
              "level": "tasks",
              "stage": null,
              "number": "0",
              "detail": null
          },
          {
              "type": "result",
              "date": "2024-11-22",
              "time": "14:27:32",
              "result_type": "Aborted",
              "level": "tasks",
              "stage": null,
              "number": "0",
              "detail": null
          },
          {
              "type": "result",
              "date": "2024-11-22",
              "time": "14:27:32",
              "result_type": "Failed",
              "level": "tasks",
              "stage": null,
              "number": "1",
              "detail": {
                  "lines": [
                      "    - google:ubuntu-24.04-64:tests/main/ack\n",
                      "error: unsuccessful run\n",
                      "\n"
                  ]
              }
          }
          ]
          EOF

      - name: Generate Data (2)
        if: ${{ inputs.group == 'nested-ubuntu-24' }}
        run: |
          mv nested.json example-${{ inputs.runner-name }}.json

      - name: Save spread test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "results-${{ github.run_id }}-${{ github.run_attempt }}-${{ inputs.runner-name }}" 
          path: "example-${{ inputs.runner-name }}.json"