name: test

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  # build:
  #   uses: ./.github/workflows/builder.yaml
  #   with:
  #     runner: ${{ matrix.runner }}
  #   strategy:
  #     matrix:
  #       runner: [ubuntu-latest, macos-latest]

  run-things:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cool-strings:
          # - string1
          - [string2, string3, string4]
        extra-cool-strings:
          - string5
          - string6
        exclude:
          - cool-strings: [string2, string3, string4]
            extra-cool-strings: string5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: String Test
        if: "endsWith(matrix.cool-strings, '1') && startsWith(matrix.cool-strings, 's')"
        run: |
          echo "${{ toJSON(matrix.cool-strings) }}"
          printf "%s" "${{ toJSON(matrix.cool-strings) }}"
          grep -q "2" <<<"${{ toJSON(matrix.cool-strings) }}"

      - name: Get PR number
        if: github.event_name == 'pull_request'
        run: |
          echo "PR number is ${{ github.event.number }}"

      - name: Comment
        if: github.event_name == 'pull_request'
        run: |
          gh pr comment 1 --body "Test comment"