name: test

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/builder.yaml
    with:
      runner: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]

  do-things:
    runs-on: ubuntu-latest
    env:
      SRC_DIR: "${{ github.workspace }}/src"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: "${{ env.SRC_DIR }}"
    - name: Do things with strings
      uses: "${{ env.SRC_DIR }}/.github/workflows/actions/strings"
      with: 
        something-extra: dude
    - name: Check file
      run: cat whatsup

  run-things:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    strategy:
      matrix:
        cool-strings:
          # - string1
          - [string2, string3, string4]
        extra-cool-strings:
          - string5
          - string6
        exclude:
          - cool-strings: [string2, string3, string4]
            extra-cool-strings: string5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: String Test
        if: "!endsWith(matrix.cool-strings, '1') || startsWith(matrix.cool-strings, 's')"
        run: |
          echo "${{ toJSON(matrix.cool-strings) }}"
          printf "%s" "${{ toJSON(matrix.cool-strings) }}"
          grep -q "2" <<<"${{ toJSON(matrix.cool-strings) }}"

      - name: Get PR number
        if: github.event_name == 'pull_request'
        run: |
          echo "PR number is ${{ github.event.number }}"
          exit 1

      - name: Comment
        if: always() && github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment "${{ github.event.number }}" --body "$(date)" --edit-last

  
  do-things-again:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Do things with strings
      uses: ./.github/workflows/actions/strings